### ISSUE TITLE
some

### ISSUE THREAD

**Issue by TNT028** [zhfeing/SchemaNet-PyTorch#1]
I'm very interested in your work, but I'm having a problem reproducing your code.
When I run 'sh 0.train_backbone.sh', it shows 'sh: 0: Can't open 0.train_backbone.sh'

While I run ' python dist_engine.py \
     --num-nodes 1 \
     --rank 0 \
     --master-url tcp://localhost:$port \
     --backend nccl \
     --multiprocessing \
    --file-name-cfg backbone \
     --cfg-filepath config/cifar_10/vanilla/deit_tiny.yaml \
     --log-dir run/cifar_10/vanilla/deit_tiny \
    --worker backbone_worker    '

there is
ModuleNotFoundError:  No module named 'cv_lib'

Have you encountered this problem, I will be very grateful if you solve this.
Thanks you!

**Comment by zhfeing** [comment]
Our code requires [cv-lib-PyTorch](https://github.com/zhfeing/cv-lib-PyTorch/tree/bootstrapping_vits). You should download this repo and checkout to tag schema_inference.

**Comment by zhfeing** [comment]
Besides, you should pull the latest version of our code and set environment variable `CV_LIB_PATH` to the directory of `cv_lib`, for example:

```bash
export CV_LIB_PATH=$HOME/path/to/cv-lib-PyTorch
```
